"""HTML email builder for literature alerts — 3-section architecture."""

import json
import os

# Words that stay lowercase in title case (unless first word)
_SMALL_WORDS = {"a", "an", "and", "as", "at", "but", "by", "for", "if", "in",
                "nor", "of", "on", "or", "so", "the", "to", "up", "yet"}


def _title_case(s: str) -> str:
    """Title-case a string, keeping small words lowercase and acronyms intact."""
    words = s.split()
    result = []
    for i, w in enumerate(words):
        if w.isupper() and len(w) <= 5:  # Keep acronyms (NPJ, BMJ, JAMA)
            result.append(w)
        elif i == 0 or w.lower() not in _SMALL_WORDS:
            result.append(w.capitalize())
        else:
            result.append(w.lower())
    return " ".join(result)


_JIF_LOOKUP: dict[str, float] = {}


def _load_jif():
    global _JIF_LOOKUP
    if _JIF_LOOKUP:
        return
    path = os.path.join(os.path.dirname(__file__), "..", "data", "jif_lookup.json")
    if os.path.exists(path):
        with open(path) as f:
            _JIF_LOOKUP = json.load(f)


def build(all_articles: dict[str, dict], date_str: str) -> str:
    """Build a single HTML email from all alert results.

    Args:
        all_articles: OrderedDict of {alert_name: {"articles": [...], "section": str, ...}}
        date_str: Date string for the email header.

    Groups alerts by section, renders sections as h2 and subsections as h3.
    """
    _load_jif()

    # Group alerts by section
    sections: dict[str, list[tuple[str, list[dict], str]]] = {}  # section -> [(name, articles, display_name)]
    section_order: list[str] = []

    for alert_name, info in all_articles.items():
        articles = info["articles"]
        if not articles:
            continue
        section = info.get("section", alert_name)
        display_name = info.get("display_name", alert_name)

        if section not in sections:
            sections[section] = []
            section_order.append(section)
        sections[section].append((alert_name, articles, display_name))

    if not sections:
        return ""

    # Build TOC and sections HTML
    toc_items = []
    html_sections = []

    for section_name in section_order:
        subsections = sections[section_name]
        total = sum(len(arts) for _, arts, _ in subsections)
        anchor = section_name.lower().replace(" ", "-").replace("×", "x")

        toc_items.append(
            f'<a href="#{anchor}" style="color:#555; text-decoration:none;">'
            f'{section_name} ({total})</a>'
        )

        # Section header
        parts = [f'<h2 id="{anchor}">{section_name} ({total})</h2>']

        # Subsection content
        if len(subsections) == 1:
            # Single subsection: no h3, just articles under h2
            _, articles, _ = subsections[0]
            parts.append(_build_articles(articles))
        else:
            # Multiple subsections: each gets h3
            for _, articles, display_name in subsections:
                parts.append(_build_subsection(display_name, articles))

        html_sections.append("\n".join(parts))

    toc = " &nbsp;&middot;&nbsp; ".join(toc_items)
    body = "\n".join(html_sections)

    return f"""\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; font-size: 14px; color: #222; max-width: 700px; margin: 0 auto; padding: 16px; }}
.toc {{ color: #555; font-size: 13px; margin-bottom: 8px; }}
h2 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; margin-top: 28px; font-size: 18px; }}
h3 {{ color: #1a1a2e; margin-top: 20px; margin-bottom: 8px; font-size: 15px; background-color: #f0f0f0; padding: 4px 8px; border-left: 3px solid #1a1a2e; }}
.article {{ margin-bottom: 14px; }}
.article a {{ color: #222; text-decoration: none; font-weight: 600; }}
.article a:hover {{ text-decoration: underline; }}
.meta {{ color: #555; font-size: 12px; margin-top: 4px; }}
.tag {{ display: inline-block; padding: 1px 7px; border-radius: 3px; margin-right: 2px; }}
.tag-journal {{ background-color: #ede8f5; color: #5b3e96; }}
.tag-preprint {{ background-color: #f5f5f5; color: #666; }}
.tag-if {{ background-color: transparent; color: #555; border: 1px solid #ccc; }}
.tag-institution {{ background-color: #fce4ec; color: #c2185b; }}
.tag-grant {{ background-color: #e3f2fd; color: #1565c0; }}
.footer {{ margin-top: 32px; padding-top: 12px; border-top: 1px solid #e0e0e0; color: #888; font-size: 12px; }}
</style>
</head>
<body>
<div class="toc">{toc}</div>
{body}
<div class="footer">Generated by research-digest</div>
</body>
</html>"""


def _build_subsection(name: str, articles: list[dict]) -> str:
    """Build h3 subsection with articles."""
    items = _build_articles(articles)
    return f"<h3>{name} ({len(articles)})</h3>\n{items}"


def _build_articles(articles: list[dict]) -> str:
    """Build article list HTML."""
    return "\n".join(_build_article(a) for a in articles)


def _build_article(art: dict) -> str:
    """Build single article HTML."""
    title = art.get("title", "Untitled")
    doi = art.get("doi", "")
    url = f"https://doi.org/{doi}" if doi else art.get("url", "#")
    authors = art.get("authors", "")
    journal = _title_case(art.get("journal", ""))
    date = art.get("date", "")
    issn = art.get("issn", "")
    source = art.get("source", "")
    is_preprint = art.get("_is_preprint", False) or source in ("medrxiv", "biorxiv", "arxiv")
    is_reporter = source == "reporter"
    activity_code = art.get("activity_code", "")

    # Build JIF string
    jif = _JIF_LOOKUP.get(issn)
    jif_str = f"2025 IF {jif:.1f}" if jif else ""

    tags = []
    if authors:
        tags.append(authors)

    # Journal/source tag
    if journal:
        if is_reporter:
            tags.append(f'<span class="tag tag-institution">{journal}</span>')
        elif is_preprint:
            tags.append(f'<span class="tag tag-preprint">{journal}</span>')
        else:
            tags.append(f'<span class="tag tag-journal">{journal}</span>')

    # Institution tag (for non-reporter entries)
    institution = art.get("institution", "")
    if institution and not is_reporter:
        tags.append(f'<span class="tag tag-institution">{institution}</span>')

    # Activity code for NIH grants (R01, K99, etc.)
    if activity_code:
        tags.append(f'<span class="tag tag-grant">{activity_code}</span>')

    # Impact factor
    if jif_str:
        tags.append(f'<span class="tag tag-if">{jif_str}</span>')

    # Date
    if date:
        tags.append(date)

    return (
        f'<div class="article">'
        f'<a href="{url}">{title}</a>'
        f'<div class="meta">{" ".join(tags)}</div>'
        f"</div>"
    )
